### ISSUE TITLE
double url 

### ISSUE THREAD

**Issue by Geronium** [nighthawkk/pyChainedProxy#5]
Hello, 

i'm trying to chain two proxy with your package, and i got a strange error, like you can see 

"223: HTTP, length: 223
	**GET http://ip-api.comhttp://ip-api.com/json HTTP/1.1**
	Proxy-Authorization: Basic ZGdmaXA6MnBjamtjRmZzNg==
	Host: ip-api.com
	Accept-Encoding: gzip, deflate, compress, identity, *
	Accept: */*
	User-Agent: urlfetch/1.2.2"
	
the url is in double inside the GET 

and the script return this error

```
"Python 2
('Check IP After proxyfying:  ', '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta type="copyright" content="Copyright (C) 1996-2018 The Squid Software Foundation and contributors">\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"><!-- \n /*\n * Copyright (C) 1996-2019 The Squid Software Foundation and contributors\n *\n * Squid software is distributed under GPLv2+ license and includes\n * contributions from numerous individuals and organizations.\n * Please see the COPYING and CONTRIBUTORS files for details.\n */\n\n/*\n Stylesheet for Squid Error pages\n Adapted from design by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'/squid-internal-static/icons/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tbackground-color:#00ff00;\n\twidth:100%;\n}\n\n/* Page displayed body content area */\n#content {\n\tpadding: 10px;\n\tbackground: #ffffff;\n}\n\n/* General text */\np {\n}\n\n/* error brief description */\n#error p {\n}\n\n/* some data which may have caused the problem */\n#data {\n}\n\n/* the error message received from the system or other software */\n#sysmsg {\n}\n\npre {\n}\n\n/* special event: FTP / Gopher directory listing */\n#dirmsg {\n    font-family: courier, monospace;\n    color: black;\n    font-size: 10pt;\n}\n#dirlisting {\n    margin-left: 2%;\n    margin-right: 2%;\n}\n#dirlisting tr.entry td.icon,td.filename,td.size,td.date {\n    border-bottom: groove;\n}\n#dirlisting td.size {\n    width: 50px;\n    text-align: right;\n    padding-right: 5px;\n}\n\n/* horizontal lines */\nhr {\n\tmargin: 0;\n}\n\n/* page displayed footer area */\n#footer {\n\tfont-size: 9px;\n\tpadding-left: 10px;\n}\n\n\nbody\n:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }\n:lang(he) { direction: rtl; }\n --></style>\n</head><body id=ERR_INVALID_URL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href=**"http://ip-api.comhttp://ip-api.com/json"**>http://ip-api.comhttp://ip-api.com/json</a>"
```

Do you have any idea what is causing this problem and how to fix it?

Thank you

**Comment by nighthawkk** [comment]
This should not happen, can i see your code snippet

**Comment by Geronium** [comment]
Hello, 

it's just the test code, but i don't use tor, and i pass directly the adress of the first proxy 

`import urlfetch
import socket
import pyChainedProxy as socks #import pyChainedProxy

# Enable debugging
def DEBUG(msg):
  print (msg)

#socks.DEBUG = DEBUG


print ("Hell:  ",urlfetch.get('http://ip-api.com/json').content)
# Configure a default chain
chain = [
#          'socks5://localhost:9050/',
          'http://1.1.2.2:3128', # squid proxy with connect rules for the tunneling
          'http://login:pass@1.1.1.1:11',

]
socks.setdefaultproxy() # Clear the default chain
#adding hops with proxies
for hop in chain:
   socks.adddefaultproxy(*socks.parseproxy(hop))

#wrap a single module
#socks.wrapmodule(urlfetch)

# Configure alternate routes (No proxy for localhost)
socks.setproxy('localhost', socks.PROXY_TYPE_NONE)
socks.setproxy('127.0.0.1', socks.PROXY_TYPE_NONE)

# This would have set proxies using the standard environment variables:
#socks.usesystemdefaults()


# Monkey Patching whole socket class (everything will be proxified)
rawsocket = socket.socket
socket.socket = socks.socksocket
# Everything will be proxied!

print ("Hell:  ",urlfetch.get('http://ip-api.com/json').content)
`

**Comment by nighthawkk** [comment]
There's must be problem with your proxy configuration, as it is working fine for me, i had setup squid proxy also, its working fine with it too.
```

'socks5://88.202.177.242:1090/',
  'http://202.61.51.204:3128/',
  http://94.179.135.230:43033/
```

Try from these proxies , if they work then it must be problem with your proxy config.

**Comment by nighthawkk** [comment]
Did this work? i am closing the issue, you can reopen it if there's any problem.

**Comment by Geronium** [comment]
Hello, yes you are right, i think the problem is in the redirection. My first proxy is a virtual machine in the cloud, and it dont take directly the wan and the internet ip.

Station computer inside the wan network -> | cloud (manage the wan and internet ip and redirect to private network) : inside the cloud my first proxy -> and after that my second proxy in the internet

Unfortunately, i don't have access to the infrastructure of the cloud, i just depend on it.  I used an other strategy, the redirection of a port of my first proxy to a second proxy.

Thank you for you help (and for this library).
