### ISSUE TITLE
Problem with Python3 - SOCKS

### ISSUE THREAD

**Issue by noobiangodd** [nighthawkk/pyChainedProxy#7]
In a previous issue: https://github.com/nighthawkk/pyChainedProxy/issues/1#issue-602561926, this was fixed for HTTP authentication, however it still occurs on SOCKS

  File "C:\Python310\lib\site-packages\pyChainedProxy\__init__.py", line 579, in __negotiatesocks5
    self.sendall(chr(0x01).encode() +
TypeError: can't concat str to bytes

**Comment by soermejo** [comment]
You just need to encode everything!
I fixed by replacing lines 580-582 in __init__.py

```
            # Okay, we need to perform a basic username/password

            # authentication.

          

            self.sendall(chr(0x01).encode() +

                         chr(len(proxy[P_USER]))**.encode()** + proxy[P_USER]**.encode()** +

                         chr(len(proxy[P_PASS]))**.encode()** + proxy[P_PASS]**.encode()**)

            authstat = self.__recvall(2)
```

**Comment by seanmcfeely** [comment]
Looks like this repo was forked from [PySocksipyChain](https://github.com/pagekite/PySocksipyChain). They look more responsive but PySocksipyChain had the same [issue](https://github.com/pagekite/PySocksipyChain/issues/11). I submitted [this PR](https://github.com/pagekite/PySocksipyChain/pull/12) to fix it with the fix described above.

Also I posted a fork of the PySocksipyChain project and published the fork (with the fix appleid) to pypi: https://pypi.org/project/sockschain/
